name: reg.ru deploy

on:
  push:
    branches:
      - "main"

jobs:
  build-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - run: npm ci
    - run: npm run prod
    - env:
        DEPLOY_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
        DEPLOY_LOGIN: ${{ secrets.DEPLOY_LOGIN }}
      run: sshpass -p "$DEPLOY_PASSWORD" rsync -avzhHl docs/* "$DEPLOY_LOGIN"@alexmalcev.space:/root/portfolio